import { type NextPage } from "next";
import Head from "next/head";
import React from "react";
import Connected from "~/components/main/connected";
import NotConnected from "~/components/main/notConnected";
import Title from "~/components/title";
import useNOSTR from "~/hooks/useNOSTR";

const Home: NextPage = () => {
  const { pubKey } = useNOSTR();

  return (
    <>
      <Head>
        <title>NOSTR Hackaton - La Crypta</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#15162c] to-[#2e026d] text-2xl text-white">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <Title />
          {pubKey ? <Connected /> : <NotConnected />}
        </div>
      </main>
    </>
  );
};

export default Home;
