import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>NOSTR Hackaton - La Crypta</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">NOSTR Hackaton</span> -
            La Crypta
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            {/* Link para Alby */}
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://getalby.com/"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Descargamos Alby →</h3>
              <div className="text-lg">
                Descargamos y configurams NOSTR en Alby
              </div>
            </Link>
            {/* Botón para conectar */}
            <button
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              onClick={() => alert("Conectamos con NOSTR")}
            >
              <h3 className="text-2xl font-bold">Conectamos →</h3>
              <div className="text-lg">Conectamos con NOSTR</div>
            </button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
